# name of your application
APPLICATION = test

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

USEMODULE += periph_i2c

include $(RIOTBASE)/Makefile.include
