ifneq (,$(filter mlx90393,$(USEMODULE)))
  USEMODULE += ztimer
  USEMODULE += ztimer_msec
endif

ifneq (,$(filter mlx90393_i2c,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter mlx90393_spi,$(USEMODULE)))
  FEATURES_REQUIRED += periph_spi
endif

ifneq (,$(filter mlx90393_woc,$(USEMODULE)))
  USEMODULE += mlx90393_int
endif

ifneq (,$(filter mlx90393_int,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
endif
